"use client";

import localFont from "next/font/local";
import Navbar from "./(components)/Layouts/Navbar";
import "./styles/globals.css";
import Footer from "./(components)/Layouts/Footer";
import { Provider } from "react-redux";
import store from "@/src/redux/store";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Blood Bank",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
          <Navbar />
          <div className="min-h-[70vh]">{children}</div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
