"use client";

import localFont from "next/font/local";
import Navbar from "../src/Components/Layouts/Navbar";
import "./styles/globals.css";
import "./styles/antdCustom.css";
import Footer from "../src/Components/Layouts/Footer";
import { Provider } from "react-redux";
import store from "@/src/redux/store";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "@/src/Hook/AuthContext";
import AuthMiddleware from "@/src/Components/Layouts/AuthMiddleware";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Blood Bank",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <>
        <body>
          {" "}
          <ToastContainer />
          <AuthProvider>
            <Provider store={store}>
              <AuthMiddleware>
                <Navbar />
                <div className="min-h-[70vh] p-2 sm:p-0">{children}</div>
                <Footer />
              </AuthMiddleware>
            </Provider>
          </AuthProvider>
        </body>
      </>
    </html>
  );
}
