"use client";

import { useEffect } from "react";
import localFont from "next/font/local";
import Script from "next/script";
import Navbar from "../src/Components/Layouts/Navbar";
import "./styles/globals.css";
import "./styles/antdCustom.css";
import Footer from "../src/Components/Layouts/Footer";
import { Provider } from "react-redux";
import store from "@/src/redux/store";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "@/src/Hook/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Blood Bank",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    // Add Google AdSense meta tag
    const metaTag = document.createElement("meta");
    metaTag.name = "google-adsense-account";
    metaTag.content = "ca-pub-3058178790781075";
    document.head.appendChild(metaTag);

    return () => {
      // Cleanup: remove meta tag on unmount (optional)
      const existingTag = document.querySelector(
        'meta[name="google-adsense-account"]'
      );
      if (existingTag) {
        document.head.removeChild(existingTag);
      }
    };
  }, []);

  return (
    <html lang="en">
      <>
        <body>
          <Script
            async
            src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3058178790781075"
            crossOrigin="anonymous"
            strategy="afterInteractive"
          />
          <ToastContainer />
          <AuthProvider>
            <Provider store={store}>
              <Navbar />
              <div className="min-h-[70vh] p-2 sm:p-0">{children}</div>
              <Footer />
            </Provider>
          </AuthProvider>
        </body>
      </>
    </html>
  );
}
